services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - mindsdb
    environment:
      - MINDSDB_HOST=mindsdb
      - MINDSDB_PORT=47334

  mindsdb:
    image: mindsdb/mindsdb:latest
    ports:
      - "47334:47334"  # Default MindsDB HTTP API port
      - "47335:47335"  # Default MindsDB MySQL port
    volumes:
      - mindsdb_data:/root/mindsdb_config
    environment:
      - MINDSDB_DATA_DIR=/root/mindsdb_config

volumes:
  mindsdb_data: